-- SQL DDL Commands Practice
-- Database: STUDENT

CREATE DATABASE STUDENT;

USE STUDENT;

CREATE TABLE STUDENT_DETAILS(
    SID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT,
    DEPARTMENT VARCHAR(30)
);

-- Modify column datatype
ALTER TABLE STUDENT_DETAILS
MODIFY AGE TINYINT;

-- Rename column
ALTER TABLE STUDENT_DETAILS
RENAME COLUMN DEPARTMENT TO DEPT;

-- Drop column
ALTER TABLE STUDENT_DETAILS
DROP COLUMN EMAIL;

-- Rename table
RENAME TABLE STUDENT_DETAILS TO STUDENTS;

-- CHANGE command practice
ALTER TABLE STUDENTS
CHANGE DEPT DEPARTMENT VARCHAR(50);


-- Employee Table Practice

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(10),
    SALARY BIGINT,
    CITY VARCHAR(20)
);

-- Modify salary datatype
ALTER TABLE EMPLOYEE
MODIFY SALARY DECIMAL(10,2);

-- Rename CITY using CHANGE
ALTER TABLE EMPLOYEE
CHANGE CITY LOCATION VARCHAR(20);

-- Rename table
RENAME TABLE EMPLOYEE TO EMP_DETAILS;
